### PR TITLE
Infer protocol from k8s service name

### PR DESCRIPTION
**Pull request by aattuluri**
Context:
https://github.com/istio-ecosystem/admiral/issues/76

This adds support for creating admiral endpoints with grpc as the protocol.

`Note:` Currently only one of http or grpc protocols is supported for a given service because there is only one port for cross cluster communication which is 15443. This support will be expanded upon auto protocol detection across clusters on the same port.

### CODE REVIEW

**Review by josephpeacock — CHANGES_REQUESTED** [review]
A few minor comments in-line. The big one is I see a few `if len(meshPorts) > 1 {` blocks, but it's not everywhere that the meshPorts is used. Let's either a) make sure we're checking that error case everywhere or b) check it in the GetMeshPorts method

More broadly, is doing nothing the right approach for a situation in which a service has multiple ports? I don't feel confident that I know the right answer here, but failing silently (even with logs) feels like an invitation for lots of future debugging time in response to the question "Why aren't I seeing a service entry for my new deployment?" Feels like something we should at least make an intentional decision on.

**Comment by josephpeacock** [comment]
@aattuluri One more thought - I see you added examples to the sample yamls, do you want to also add the accompanying instructions here https://github.com/istio-ecosystem/admiral/blob/master/docs/Examples.md?

**Comment by aattuluri** [comment]
> A few minor comments in-line. The big one is I see a few `if len(meshPorts) > 1 {` blocks, but it's not everywhere that the meshPorts is used. Let's either a) make sure we're checking that error case everywhere or b) check it in the GetMeshPorts method
> 
> More broadly, is doing nothing the right approach for a situation in which a service has multiple ports? I don't feel confident that I know the right answer here, but failing silently (even with logs) feels like an invitation for lots of future debugging time in response to the question "Why aren't I seeing a service entry for my new deployment?" Feels like something we should at least make an intentional decision on.

Valid point, this made me thinking into keeping the behavior backward compatible and also consistent. This approach will pick the first port/protocol when more than one is present and logs a warning if that multi port support isn't there.

**Comment by josephpeacock** [comment]
I think that makes a lot of sense.

**Review by josephpeacock — APPROVED** [review]
lgtm

**Comment by josephpeacock** [comment]
You'll have to go fix the sign-off. But once that's done and the build passes, I'd say it looks good!

**Pull request merged**
